// configuration for an easy game
const TOTAL_ATTEMPTS_EASY = 10;
const TOTAL_HINTS_EASY = 3;
const TOTAL_GUESSES_REMAINED_EASY = 10;
const CODE_LEN_EASY = 4;

// configuration for a medium game
const TOTAL_ATTEMPTS_MEDIUM = 7;
const TOTAL_HINTS_MEDIUM = 2;
const TOTAL_GUESSES_REMAINED_MEDIUM = 7;
const CODE_LEN_MEDIUM = 4;

// configuration for a hard game
const TOTAL_ATTEMPTS_HARD = 12;
const TOTAL_HINTS_HARD = 0;
const TOTAL_GUESSES_REMAINED_HARD = 12;
const CODE_LEN_HARD = 4;

module.exports = {
	TOTAL_ATTEMPTS_EASY,
	TOTAL_HINTS_EASY,
	TOTAL_GUESSES_REMAINED_EASY,
	CODE_LEN_EASY,
	TOTAL_ATTEMPTS_MEDIUM,
	TOTAL_HINTS_MEDIUM,
	TOTAL_GUESSES_REMAINED_MEDIUM,
	CODE_LEN_MEDIUM,
	TOTAL_ATTEMPTS_HARD,
	TOTAL_HINTS_HARD,
	TOTAL_GUESSES_REMAINED_HARD,
	CODE_LEN_HARD,
};
